require "user.launch"
require "user.options"
require "user.keymaps"
spec "user.colorscheme"
spec "user.treesitter"
spec "user.devicons"
spec "user.mason"
spec "user.nvim-tree"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.autopairs"
-- spec "user.rainbow"
-- spec "user.ibl"
spec "user.gitsigns"
spec "user.bufferline"
spec "user.alpha"
spec "user.comment"
spec "user.toggleterm"
spec "user.which-key"
spec "user.illuminate"
spec "user.lualine"
spec "user.markdown-preview"
-- spec "user.none-ls"
spec "user.neogit"
spec "user.surround"
spec "user.dispatch"
-- spec "user.vimtex"
require "user.plugins"
